apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: gateway-service
build:
  artifacts:
      jib: 
        fromImage: 'eclipse-temurin:sha256:ec91b7d1c3c31a9183f73f9e6279d26021f25dcc09f5d33fe03b153c6ed64120'
    #   custom:
    #     buildCommand: |
    #       mvn clean package && 7z x target/gateway-service-1.2.war -otarget/exploded && docker build -t $IMAGE -f Dockerfile.dev $BUILD_CONTEXT
    #     dependencies:
    #       paths:
    #       - target/classes
    #       - Dockerfile.dev
    #       ignore:
    #       - target/exploded
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - ../k8s/privileges.yaml
    - k8s/**.yaml
