kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kamysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamysql
  labels:
    app: kamysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamysql
  template:
    metadata:
      labels:
        app: kamysql
    spec:
      volumes:
      - name: kamysql-pv-storage
        persistentVolumeClaim:
          claimName: kamysql-pv-claim
      containers:
      - name: kamysql
        image: vulhub/mysql:5.5.23
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: kamysql-pv-storage
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kamysql
  labels:
    app: kamysql
spec:
  ports:
  - port: 33060
    targetPort: 3306
    protocol: TCP
  selector:
    app: kamysql